import React, { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { Camera, ImagePlus, ArrowLeft, Sun, Focus, ScanLine, SquareStack, RotateCcw, CheckCircle, AlertCircle } from 'lucide-react';
import Button from '../components/ui/Button';
import CameraCapture from '../components/scanner/CameraCapture';
import Loader from '../components/ui/Loader';
import useCamera from '../hooks/useCamera';
import useClassifier from '../hooks/useClassifier';
import useHistory from '../hooks/useHistory';
import { fileToDataUrl, compressImage } from '../utils/imageUtils';

/** Scan page states */
const SCAN_STATE = {
  IDLE: 'idle',
  CAMERA: 'camera',
  PREVIEW: 'preview',
  ANALYZING: 'analyzing',
  ERROR: 'error',
};

const SCAN_INSTRUCTIONS = [
  { icon: Sun, title: 'Pencahayaan Cukup', desc: 'Pastikan area terang untuk hasil terbaik' },
  { icon: Focus, title: 'Fokus pada Objek', desc: 'Satu jenis sampah per scan' },
  { icon: ScanLine, title: 'Gambar Jelas', desc: 'Hindari foto yang blur atau buram' },
  { icon: SquareStack, title: 'Background Bersih', desc: 'Latar belakang yang tidak ramai' },
];

/**
 * Scan page — Camera capture or file upload with AI analysis
 */
const ScanPage = () => {
  const navigate = useNavigate();
  const fileInputRef = useRef(null);

  const [scanState, setScanState] = useState(SCAN_STATE.IDLE);
  const [capturedImage, setCapturedImage] = useState(null); // { dataUrl, base64 }
  const [analysisError, setAnalysisError] = useState(null);

  const camera = useCamera();
  const classifier = useClassifier();
  const { addToHistory } = useHistory();

  /** Start camera mode */
  const handleStartCamera = async () => {
    setScanState(SCAN_STATE.CAMERA);
    await camera.startCamera();
  };

  /** Capture photo from camera */
  const handleCapture = async () => {
    const photo = camera.capturePhoto();
    if (!photo) return;

    camera.stopCamera();
    const { base64: compressedB64, dataUrl: compressedDataUrl } = await compressImage(photo.dataUrl);
    setCapturedImage({ dataUrl: compressedDataUrl, base64: compressedB64 });
    setScanState(SCAN_STATE.PREVIEW);
  };

  /** Handle file upload from gallery */
  const handleFileUpload = async (event) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const dataUrl = await fileToDataUrl(file);
    const { base64, dataUrl: compressed } = await compressImage(dataUrl);
    setCapturedImage({ dataUrl: compressed, base64 });
    setScanState(SCAN_STATE.PREVIEW);
    // Reset input value so the same file can be re-selected
    event.target.value = '';
  };

  /** Analyze the captured/uploaded image */
  const handleAnalyze = async () => {
    if (!capturedImage) return;

    setScanState(SCAN_STATE.ANALYZING);
    setAnalysisError(null);

    // Backend now returns the fully saved historyItem directly
    const historyItem = await classifier.analyze(capturedImage.base64);

    if (historyItem && historyItem.id) {
      // Save to local history (localStorage)
      addToHistory(historyItem);
      
      // Navigate to result page using the ID generated by the backend
      navigate(`/result/${historyItem.id}`, { state: { result: historyItem.result, imageDataUrl: capturedImage.dataUrl } });
    } else {
      setAnalysisError(classifier.error || 'Analisis gagal. Coba lagi.');
      setScanState(SCAN_STATE.ERROR);
    }
  };

  /** Reset to idle state */
  const handleReset = () => {
    camera.stopCamera();
    setCapturedImage(null);
    setAnalysisError(null);
    classifier.reset();
    setScanState(SCAN_STATE.IDLE);
  };

  return (
    <div className="scan-page animate-slide-up">
      {/* Left panel — instructions */}
      <aside className="scan-page__sidebar" aria-label="Instruksi scan">
        <h1 className="scan-page__sidebar-title">Instruksi Scan</h1>
        <div className="scan-instructions" role="list">
          {SCAN_INSTRUCTIONS.map(({ icon: Icon, title, desc }) => (
            <div key={title} className="scan-instruction" role="listitem">
              <div className="scan-instruction__icon" aria-hidden="true">
                <Icon size={18} color="var(--color-primary)" />
              </div>
              <div>
                <strong className="scan-instruction__title">{title}</strong>
                <p className="scan-instruction__desc">{desc}</p>
              </div>
            </div>
          ))}
        </div>

        <Button
          variant="ghost"
          size="sm"
          icon={<ArrowLeft size={16} />}
          onClick={() => navigate('/')}
          id="btn-back-home"
          aria-label="Kembali ke beranda"
          style={{ marginTop: 'auto' }}
        >
          Kembali
        </Button>
      </aside>

      {/* Right panel — main content */}
      <main className="scan-page__main">
        {/* IDLE STATE */}
        {scanState === SCAN_STATE.IDLE && (
          <div className="scan-idle animate-fade-in">
            <div className="scan-idle__options">
              <button
                className="scan-option-card"
                onClick={handleStartCamera}
                id="btn-open-camera"
                aria-label="Buka kamera untuk scan sampah"
              >
                <div className="scan-option-card__icon-wrapper">
                  <Camera size={36} color="var(--color-primary)" />
                </div>
                <strong className="scan-option-card__title">Scan dengan Kamera</strong>
                <p className="scan-option-card__desc">Arahkan kamera ke sampah secara langsung</p>
              </button>

              <button
                className="scan-option-card"
                onClick={() => fileInputRef.current?.click()}
                id="btn-upload-file"
                aria-label="Upload foto sampah dari galeri"
              >
                <div className="scan-option-card__icon-wrapper" style={{ background: '#EFF6FF' }}>
                  <ImagePlus size={36} color="#3B82F6" />
                </div>
                <strong className="scan-option-card__title">Upload dari Galeri</strong>
                <p className="scan-option-card__desc">Pilih foto sampah dari perangkatmu</p>
              </button>
            </div>

            <input
              ref={fileInputRef}
              type="file"
              accept="image/*"
              onChange={handleFileUpload}
              className="sr-only"
              id="file-input-gallery"
              aria-label="Pilih file gambar"
            />

            <p className="scan-idle__hint">
              Pastikan pencahayaan cukup dan objek terlihat jelas untuk hasil terbaik
            </p>
          </div>
        )}

        {/* CAMERA STATE */}
        {scanState === SCAN_STATE.CAMERA && (
          <div className="scan-camera animate-fade-in">
            <CameraCapture
              videoRef={camera.videoRef}
              isActive={camera.isActive}
              isLoading={camera.isLoading}
              error={camera.error}
              onCapture={handleCapture}
              onToggleCamera={camera.toggleCamera}
              onStop={handleReset}
              facingMode={camera.facingMode}
            />
          </div>
        )}

        {/* PREVIEW STATE */}
        {scanState === SCAN_STATE.PREVIEW && capturedImage && (
          <div className="scan-preview animate-slide-up">
            <div className="scan-preview__image-wrapper">
              <img
                src={capturedImage.dataUrl}
                alt="Foto sampah yang akan dianalisis"
                className="scan-preview__image"
              />
              <div className="scan-preview__image-overlay" aria-hidden="true">
                <CheckCircle size={24} color="white" />
                <span>Foto siap dianalisis</span>
              </div>
            </div>

            <div className="scan-preview__actions">
              <Button
                variant="outline"
                size="md"
                icon={<RotateCcw size={16} />}
                onClick={handleReset}
                id="btn-retake"
                aria-label="Ulangi foto"
              >
                Ulangi
              </Button>
              <Button
                variant="primary"
                size="md"
                icon={<ScanLine size={16} />}
                onClick={handleAnalyze}
                id="btn-analyze"
                aria-label="Analisis gambar dengan AI"
                fullWidth
              >
                Analisis Sekarang
              </Button>
            </div>
          </div>
        )}

        {/* ANALYZING STATE */}
        {scanState === SCAN_STATE.ANALYZING && (
          <div className="scan-analyzing animate-fade-in">
            {capturedImage && (
              <img
                src={capturedImage.dataUrl}
                alt="Gambar sedang dianalisis"
                className="scan-analyzing__thumbnail"
              />
            )}
            <Loader
              text="Menganalisis sampah..."
              progress={classifier.progress}
            />
          </div>
        )}

        {/* ERROR STATE */}
        {scanState === SCAN_STATE.ERROR && (
          <div className="scan-error animate-bounce-in">
            <div className="scan-error__icon" aria-hidden="true">
              <AlertCircle size={48} color="#EF4444" />
            </div>
            <h2 className="scan-error__title">Analisis Gagal</h2>
            <p className="scan-error__message">{analysisError}</p>
            <div className="scan-error__actions">
              <Button
                variant="primary"
                onClick={handleReset}
                id="btn-try-again"
                aria-label="Coba lagi"
              >
                Coba Lagi
              </Button>
            </div>
          </div>
        )}
      </main>

      <style>{`
        .scan-page {
          display: grid;
          grid-template-columns: 320px 1fr;
          min-height: 100vh;
        }

        /* ---- Sidebar ---- */
        .scan-page__sidebar {
          padding: 28px 24px;
          background: var(--color-white);
          border-right: 1px solid var(--color-border);
          display: flex;
          flex-direction: column;
          gap: 20px;
        }

        .scan-page__sidebar-title {
          font-size: 1.25rem;
          font-weight: 700;
          margin: 0;
        }

        .scan-instructions {
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .scan-instruction {
          display: flex;
          align-items: flex-start;
          gap: 12px;
        }

        .scan-instruction__icon {
          width: 36px;
          height: 36px;
          border-radius: var(--radius-md);
          background: var(--color-primary-bg);
          display: flex;
          align-items: center;
          justify-content: center;
          flex-shrink: 0;
          border: 1px solid var(--color-primary-bg-md);
        }

        .scan-instruction__title {
          display: block;
          font-size: 0.875rem;
          font-weight: 700;
          color: var(--color-text-primary);
          font-family: var(--font-heading);
          margin-bottom: 2px;
        }

        .scan-instruction__desc {
          font-size: 0.8rem;
          color: var(--color-text-secondary);
          margin: 0;
          line-height: 1.4;
        }

        /* ---- Main Content ---- */
        .scan-page__main {
          background: var(--color-dark-bg);
          display: flex;
          align-items: center;
          justify-content: center;
          min-height: 100%;
          padding: 20px;
        }

        /* ---- Idle ---- */
        .scan-idle {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 28px;
          width: 100%;
          max-width: 520px;
        }

        .scan-idle__options {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 16px;
          width: 100%;
        }

        .scan-option-card {
          background: rgba(255,255,255,0.05);
          border: 1.5px solid rgba(255,255,255,0.1);
          border-radius: var(--radius-xl);
          padding: 28px 20px;
          cursor: pointer;
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 12px;
          text-align: center;
          transition: all var(--transition-normal);
          color: white;
        }

        .scan-option-card:hover {
          background: rgba(255,255,255,0.09);
          border-color: var(--color-primary);
          transform: translateY(-4px);
          box-shadow: 0 8px 24px rgba(34, 197, 94, 0.15);
        }

        .scan-option-card__icon-wrapper {
          width: 72px;
          height: 72px;
          background: var(--color-primary-bg);
          border-radius: var(--radius-lg);
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .scan-option-card__title {
          font-family: var(--font-heading);
          font-size: 0.9375rem;
          font-weight: 700;
          color: white;
        }

        .scan-option-card__desc {
          font-size: 0.8125rem;
          color: rgba(255,255,255,0.6);
          margin: 0;
          line-height: 1.4;
        }

        .scan-idle__hint {
          font-size: 0.8125rem;
          color: rgba(255,255,255,0.5);
          text-align: center;
          margin: 0;
          max-width: 360px;
          line-height: 1.5;
        }

        /* ---- Camera ---- */
        .scan-camera {
          width: 100%;
          max-width: 640px;
          height: 560px;
        }

        /* ---- Preview ---- */
        .scan-preview {
          display: flex;
          flex-direction: column;
          gap: 20px;
          width: 100%;
          max-width: 460px;
        }

        .scan-preview__image-wrapper {
          position: relative;
          border-radius: var(--radius-xl);
          overflow: hidden;
          background: #000;
          aspect-ratio: 4/3;
        }

        .scan-preview__image {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .scan-preview__image-overlay {
          position: absolute;
          bottom: 0;
          left: 0;
          right: 0;
          background: linear-gradient(transparent, rgba(0,0,0,0.6));
          padding: 20px 16px 14px;
          display: flex;
          align-items: center;
          gap: 8px;
          color: white;
          font-size: 0.875rem;
          font-weight: 600;
        }

        .scan-preview__actions {
          display: flex;
          gap: 12px;
        }

        /* ---- Analyzing ---- */
        .scan-analyzing {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 0;
        }

        .scan-analyzing__thumbnail {
          width: 100px;
          height: 100px;
          border-radius: var(--radius-xl);
          object-fit: cover;
          border: 3px solid var(--color-primary);
          box-shadow: var(--shadow-green);
        }

        /* ---- Error ---- */
        .scan-error {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 16px;
          text-align: center;
          padding: 40px;
        }

        .scan-error__title {
          color: white;
          font-size: 1.25rem;
          margin: 0;
        }

        .scan-error__message {
          color: rgba(255,255,255,0.7);
          font-size: 0.9rem;
          margin: 0;
          max-width: 320px;
        }

        /* ---- Responsive ---- */
        @media (max-width: 1023px) {
          .scan-page {
            grid-template-columns: 280px 1fr;
          }
        }

        @media (max-width: 767px) {
          .scan-page {
            grid-template-columns: 1fr;
          }

          .scan-page__sidebar {
            border-right: none;
            border-bottom: 1px solid var(--color-border);
            padding: 20px;
          }

          .scan-idle__options {
            grid-template-columns: 1fr;
          }

          .scan-camera {
            height: 440px;
          }
        }
      `}</style>
    </div>
  );
};

export default ScanPage;
